default:
	clang evenChange.c -o evenChange.run -Wall -Werror
	clang hello.c -o hello.run -Wall -Werror
	clang mario.c -o mario.run -Wall -Werror
	clang water.c -o water.run -Wall -Werror
	clang credit.c -o credit.run -Wall -Werror

clean:
	rm *.run