default:
	clang evenChange.c -o evenChange.run -Wall -Werror
	clang hello.c -o hello.run -Wall -Werror
	clang mario.c -o mario.run -Wall -Werror
	clang water.c -o water.run -Wall -Werror

clean:
	rm *.run

hello:
	clang hello.c -o hello.run -Wall -Werror
	./hello.run
	rm hello.run

mario:
	clang mario.c -o mario.run -Wall -Werror
	./mario.run
	rm mario.run

water:
	clang water.c -o water.run -Wall -Werror
	./water.run
	rm water.run

evenChange:
	clang evenChange.c -o evenChange.run -Wall -Werror
	./evenChange.run
	rm evenChange.run
