"""
This type stub file was generated by pyright.
"""

import os
import sys

__all__ = ["get_info", "show"]
extra_dll_dir = os.path.join(os.path.dirname(__file__), '.libs')
if sys.platform == 'win32' and os.path.isdir(extra_dll_dir):
    ...
blas_mkl_info = {  }
blis_info = {  }
openblas_info = { 'libraries': ['openblas', 'openblas'],'library_dirs': ['/usr/local/lib'],'language': 'c','define_macros': [('HAVE_CBLAS', None)] }
blas_opt_info = { 'libraries': ['openblas', 'openblas'],'library_dirs': ['/usr/local/lib'],'language': 'c','define_macros': [('HAVE_CBLAS', None)] }
lapack_mkl_info = {  }
openblas_lapack_info = { 'libraries': ['openblas', 'openblas'],'library_dirs': ['/usr/local/lib'],'language': 'c','define_macros': [('HAVE_CBLAS', None)] }
lapack_opt_info = { 'libraries': ['openblas', 'openblas'],'library_dirs': ['/usr/local/lib'],'language': 'c','define_macros': [('HAVE_CBLAS', None)] }
def get_info(name):
    ...

def show():
    ...

